version: 2
jobs:
  build:
    working_directory: ~/bostonhacks-static
    steps:
      - checkout
      - deploy:
          name: deploy-bostonhacks-headstart-prod
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              scp -o StrictHostKeyChecking=no -r ~/bostonhacks-static/index.html circleci@${BOSTONHACKS_IP_ADDR}:/var/www/bostonhacks-static/
            fi